#!/usr/bin/env bash
set -e

src=$HOME/Repos/tmux/tmux.conf
dst=$HOME/.tmux.conf

ln -svf "$src" "$dst"

if [ ! -d ~/.tmux/plugins/tpm/.git ]; then
    echo "Installing TPM"
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
else
    echo "TPM Already Installed"
fi
