#!/usr/bin/env bash

cp ./tmux.conf ~/.tmux.conf

if [ ! -d ~/.tmux/plugins/tpm/.git ]; then
    echo "Installing TPM"
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
else
    echo "TPM Already Installed"
fi
